name: Changed Files Pre-Commit Check

on: [push, pull_request]
permissions:
  contents: write

jobs:
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 10
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install pre-commit
        run: pip install pre-commit

      - id: changed-files
        name: Check changed files
        uses: dorny/paths-filter@v4
        with:
          token: ${{ github.token }}
          list-files: shell
          filters: |
            repo:
              - added|modified: ['**']

      - name: Cache pre-commit environments
        run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Check ALL Files On Branch
        if: github.event_name != 'pull_request'
        run: pre-commit run --all-files

      - name: Run pre-commit (apply fixes) for PR
        if: github.event_name == 'pull_request'
        run: |
          pre-commit run --files ${{ steps.changed-files.outputs.repo_files }} || true

      - name: Commit autofixes for PR
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "apply pre-commit fixes"

      - name: Verify pre-commit for PR
        if: github.event_name == 'pull_request'
        run: |
          pre-commit run --files ${{ steps.changed-files.outputs.repo_files }}
