name: Changed Files Pre-Commit Check

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 10
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install pre-commit
        run: pip install pre-commit

      - id: changed-files
        name: Determine changed files
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v4
        with:
          token: ${{ github.token }}
          list-files: shell
          filters: |
            repo:
              - added|modified: ['**']

      - name: Generate cache key
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit environments
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit on Push
        if: github.event_name != 'pull_request'
        run: |
          pre-commit run --all-files --colors=always || true

      # - name: Commit fixes on Push
      #   if: github.event_name != 'pull_request'
      #   uses: stefanzweifel/git-auto-commit-action@v7
      #   with:
      #    commit_message: "apply pre-commit fixes"

      - name: Run pre-commit on changed files for PR
        if: github.event_name == 'pull_request'
        run: |
          pre-commit run --colors=always --files ${{ steps.changed-files.outputs.repo_files }} || true

      - name: Commit fixes for PR
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "apply pre-commit fixes for PR"
